### ISSUE TITLE
⛏️ Write test to change the Content-Type header to get CSRF on GraphQL APIs

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#108]
💭 Introduction:

🎯 Requirements:

✅ Task summary:
Write test to change the Content-Type header to get CSRF https://0xn3va.gitbook.io/cheat-sheets/web-application/graphql-vulnerabilities#bypass-of-csrf-protection

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This is duplicate of https://github.com/akto-api-security/akto/issues/109
