### ISSUE TITLE
⛏️ Write test for error exception traces for GraphQL APIs

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#117]
💭 Introduction:
GraphQL has gained a lot of popularity and love from the dev world. Its flexibility is one of the most powerful features. At the same time, it makes it very easy for devs to understand the root cause for any API-related problem. The excessive error description should NOT be available in prod mode. 

🎯 Requirements:
- Basic experience with **Java** 
- Basic experience with **GraphQL**

✅ Task summary:
- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Search for `Mask errors` [here](https://www.apollographql.com/blog/graphql/security/9-ways-to-secure-your-graphql-api-security-checklist/). 
- [ ] The task is to detect if `stacktrace` comes in the output because of a malformed query
- [ ] Create a file `ExceptionTracesGraphQLTest.java`. You should write a test based on an already existing GraphQL test (yet to be added here by @ankush-jain-akto). 
- [ ] Malform the query. For example, add "aktoXYZ" as a property. 
- [ ] Check if the response contains `stacktrace` in the output (case insensitive search). 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This has been implemented already. Closing the issue.
