### ISSUE TITLE
⚡️ Bug: Broken sorting functionality 

### ISSUE THREAD

**Issue by shivam-rawat-akto** [akto-api-security/akto#126]
💭 Introduction:

**Akto's** tables offer a filtering and sorting feature, allowing users to organise table content. However, the current string-based sorting method can cause issues when attempting to sort time-based parameters, like **last_seen**

🎯 Requirements:

- Experience with **Vue.js** 

✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Understand how we do it for `Observe` > `API Changes` > `New parameters` > `Discovered` column. You can find the relevant code in [Changes.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/changes/Changes.vue#L329). We should pass a `type` for integer headers and a min-max pair. 
- [ ] Implement a similar change for `New endpoints` table in the same file at [line 223](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/changes/Changes.vue#L223). Note that this doesn't use `ServerTable` directly. *SimpleTable* is for creating tables when you have all the data in the UI. *ServerTable* is for creating tables where only 1 page is fetched from backend. Any changes in filters/sort triggers a backend query for ServerTable. 
- [ ] You will have to understand how `SimpleTable` uses `ServerTable` for its implementation.
- [ ] To sort columns based on time, sort them according to epochs instead of treating them as strings.
- [ ] Submit a pull request in 
 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This has been fixed in the new Polaris UI. Closing the issue
