### ISSUE TITLE
⚡️ Fix search in test library to support search on tests instead of categories

### ISSUE THREAD

**Issue by ayushaga14** [akto-api-security/akto#128]
💭 Introduction:
Users can go to test libraries section and search for specific test categories by specifying keywords in search categories section.
This task involves adding ability to search tests using keywords instead of searching categories.

🎯 Requirements:
Understanding of Vue js.

✅ Task summary:
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Build filtering logic on test data instead of category data.
- [ ] Submit a pull request here.

✌🏻 Hints
Currently the logic resides in filterOnSearchText method inside PageMarketplace.vue. It uses filter method for filtering out data given a search text.

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This has been implemented already. Closing the issue.
