### ISSUE TITLE
⛏️  Write test for fetching metadata from a GCP compute engine instance

### ISSUE THREAD

**Issue by aktoboy** [akto-api-security/akto#139]
💭 Introduction:
We want to test whether API's which take in url as a param are vulnerable to fetch information related to compute engine using SSRF. You can refer [this](https://hackerone.com/reports/341876) blog for more details about the attack.

🎯 Requirements:
This test should only run for APIs which are taking url as a parameter in input.
The test should correctly detect whether some instance-related information can be fetched via an API specific to GCP cloud.
An example for AWS is implemented [here](https://github.com/akto-api-security/tests-library/blob/master/Server-Side-Request-Forgery/SSRFOnAwsMetaEndpoint.yaml) already.

📚 Reading
You can find a detailed documentation of test editor rules [here](https://docs.akto.io/test-editor/test-yaml-syntax-detailed)
Find 100+ examples of YAML tests [here](https://github.com/akto-api-security/tests-library)

✅ Task summary:
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Fork the [tests-library](https://github.com/akto-api-security/tests-library) repository, create a new branch and commit the yaml file which will be called in your test.
- [ ] Signup for [Akto](https://app.akto.io)
- [ ] Check in the `Attempt` tab, if the payload changes, then task is done.
- [ ] Submit the PR here.

✌🏻 Hints:
You can build the yaml template by referring this [link](https://github.com/akto-api-security/tests-library/blob/master/Server-Side-Request-Forgery/SSRFOnAwsMetaEndpoint.yaml)

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ShatilKhan** [comment]
All right!
Then I'll follow the updated instructions 
Thanks!

**Comment by ankush-jain-akto** [comment]
Hi @ShatilKhan - updated instructions. Feel free to ask for any help 👍 😃

**Comment by rashmibharambe** [comment]
> Hi @ShatilKhan - updated instructions. Feel free to ask for any help 👍 😃

@ankush-jain-akto @ShatilKhan if you are not working on this can I take this up?

**Comment by avneesh-akto** [comment]
I've assigned it to you, @rashmibharambe  . Happy hacking! Feel free to join our [Discord](https://discord.com/channels/1070706429402562733/1095281477748543618) if you need assistance.

**Comment by rashmibharambe** [comment]
@avneesh-akto i have raised PR Please review- https://github.com/akto-api-security/tests-library/pull/36

**Comment by avneesh-akto** [comment]
LGTM 🚀 . Will soon merge the PR. Thank you for your submission.
