### ISSUE TITLE
⛏️ Write a detect SSRF vulnerability in gRPC

### ISSUE THREAD

**Issue by aktoboy** [akto-api-security/akto#144]
💭 Introduction:

🎯 Requirements:

✅ Task summary:

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by piyushpandey2000** [comment]
I would like to do this

**Comment by ankush-jain-akto** [comment]
Not enough information
