### ISSUE TITLE
⚡️Simplify Integration: Include AWS and GCP as Traffic Sources in Settings > Integrations

### ISSUE THREAD

**Issue by shivam-rawat-akto** [akto-api-security/akto#150]
💭 Introduction:

**Akto** facilitates the creation of an API inventory, which can be tested to identify potential vulnerabilities. This inventory can be generated through various channels, including AWS, GCP, and burp or har file uploads. Integration with AWS and GCP is available through the `Quick start` option in the left-navigation, while burp integration can also be accessed through `My accounts` > `Settings` > `Integrations` > `Traffic sources`. To streamline integrations, we aim to include AWS and GCP in the `Traffic sources` section for a unified experience in Akto.

🎯 Requirements:

- Experience with **Vue.js** 

✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Understand how we show it on Quick Start page - `PageQuickStart.vue` shows all. It has a slot `data-sources-content`. This slot is filled by multiple entries using `SingleDataSource.vue` component. We will have to use `SingleDataSource` component with right parameters
- [ ] Understand how `Integrations` are shown today inside settings from [IntegrationSelector.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/settings/components/integrations/IntegrationSelector.vue#L70). We need to add `AWS` and `GCP` to `Traffic Sources` item to this object. It should render the components from the point no. 4 above. 
- [ ] Add AWS and GCP traffic sources.
- [ ] Submit a pull request here
 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This is completed by @Ark2307 . Closing this issue.
