### ISSUE TITLE
⚡️Bug: Copy as curl not working for some cases

### ISSUE THREAD

**Issue by shivamrawat101192** [akto-api-security/akto#153]
💭 Introduction:

**Akto** provides a functionality called `copy as curl` via which users can copy the api request as a curl command and test it directly via terminal. This functionality seems to be broken for some cases. We aim to fix this issue for smooth user experience.

🎯 Requirements:

- Experience with **Vue.js** 

✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] There are 2 ways to copy to clipboard. Read the blog [here](https://visualbean.medium.com/how-to-copy-to-clipboard-with-vuejs-a1b7ffb1170e). The legacy one fails some times (no idea! - I think because`.focus()` is missing). Implement both these functionalities. 
- [ ] Edit `SampleSingleSide.vue` file - line 101
- [ ] Fix all the issues with this feature
- [ ] Submit a pull request in 
 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by TheSpeedX** [comment]
Hey @Ankita28g Can you assign this to me?

**Comment by Ankita28g** [comment]
Yes assigning this to you @TheSpeedX. Happy hackfesting 🎊

**Comment by TheSpeedX** [comment]
I have made suggested changes @shivamrawat101192 @ankush-jain-akto. I will need some scenarios in which the previous copy used to fail to verify the working.

**Comment by Ankita28g** [comment]
Hi @TheSpeedX thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by Ankita28g** [comment]
@TheSpeedX  Add details in this form for your [prizes](https://forms.gle/Nam3PVREYoMuPTNH9)

**Comment by Ankita28g** [comment]
hi, let me know once done.

**Comment by TheSpeedX** [comment]
Hi @Ankita28g Thanks, I have filled this !!
