### ISSUE TITLE
⚡️Implement a 'No Issues Found' State to Improve User Experience

### ISSUE THREAD

**Issue by shivam-rawat-akto** [akto-api-security/akto#156]
💭 Introduction:

**Akto** allows users to run various tests on APIs to identify vulnerabilities. Whenever an issue is detected, it appears on the `Issues` tab located on the left-navigation menu. However, currently, when there are no issues available, the page remains blank, which can lead to confusion for users. To enhance the user experience, we would like to add a `No Issues Found` page that clearly communicates to the user that there are no issues available to view."

🎯 Requirements:

- Experience with **Vue.js** 

✅ Task summary:

- [x] Ask to be assigned to the issue. 
- [x] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] Add a condition in `PageIssues.vue` file, around [line 15](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/issues/PageIssues.vue#L15). 
- [ ] Add a `v-if issues.length == 0`. In `v-else` show a message saying `No data available` with class `grey-text`
- [ ] Submit a pull request here
 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by akshatvirmani** [comment]
Hi! I would like to work on this issue.

**Comment by Ankita28g** [comment]
Hi @akshatvirmani assigning you the issue! Happy hackfesting 🎉

**Comment by akshatvirmani** [comment]
Hi, I having a bit trouble with setting up the project locally. Will try and let you know if I need help with the setup.

**Comment by ankush-jain-akto** [comment]
Hi @akshatvirmani - try setting up using VSCode dev containers [here](https://github.com/akto-api-security/akto#quicksetup-using-vscode-devcontainers)? 
If you still face issues, feel free to discuss on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Ankita28g** [comment]
https://www.youtube.com/watch?v=71tMSXcnjqM&t=696s here you go @akshatvirmani

**Comment by Ankita28g** [comment]
Hi @akshatvirmani thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

1. Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
2. Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by falconcode16** [comment]
Hey @notshivansh, can you assign this issue to me? I'll be working on this issue. Also, is there any previous work done by @akshatvirmani, or shall I complete this issue from scratch?

**Comment by ankush-jain-akto** [comment]
Hi @falconcode16 - this has been implemented already. I am closing the issue.

**Comment by ankush-jain-akto** [comment]
@falconcode16 - try your hands on this one instead 😃 
https://github.com/akto-api-security/akto/issues/155
