### ISSUE TITLE
⚡ Delete test run

### ISSUE THREAD

**Issue by notshivansh** [akto-api-security/akto#157]
💭 Introduction: Test runs can be scheduled or run once. Add a delete option to active tests. 

🎯 Requirements:

- A basic understading of vue.js, java and mongodb java sdk

✅ Task summary: 

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours
- [ ] Add a delete option. The delete option should remove the testingRun from the database.
- [ ] Submit a pull request here.

💡 Hints: 
  
- A delete option can be added in the [APICollectionGroup.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/shared/components/menus/ApiCollectionGroup.vue) file.  It has a loop which shows all the active test runs. Try to explore this part to add a delete button. 
- Deletion, as a functionality should be allowed only on recurring tests or tests scheduled for a later time but not running right now. It should not be allowed on currently running tests.
- Testing runs are stored as described in [TestingRun.java](https://github.com/akto-api-security/akto/blob/master/libs/dao/src/main/java/com/akto/dto/testing/TestingRun.java) 
- To check how API calls are implemented, check [StartTestAction.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/main/java/com/akto/action/testing/StartTestAction.java). Take reference from it and add a method to delete a testing Run. Also check the ```retrieveAllCollectionTests()``` function in the same file for more context on how to write the function.
- The api calls for the same happen via [api.js](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/testing/api.js) with the mutations happening in the  [module.js](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/testing/store/module.js) file.
 
🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by falconcode16** [comment]
Hey @notshivansh, can you assign this issue to me? I'll be working on this issue.

**Comment by ankush-jain-akto** [comment]
Hi @falconcode16 - this has been shipped already. Opened by mistake.
Closing it now. Can you please pick https://github.com/akto-api-security/akto/issues/156 instead?
