### ISSUE TITLE
⚡ Remove ghost buttons on inventory page

### ISSUE THREAD

**Issue by notshivansh** [akto-api-security/akto#160]
💭 Introduction: The inventory page, with all the API endpoints has 4 buttons, namely 'first 50', 'previous 50', 'next 50', 'last 50'. The 'first 50' and 'last 50' buttons are hidden, but still accessible.

🎯 Requirements:

- A basic understanding of vue.js

✅ Task summary: Remove the 'first 50' and 'last 50' buttons entirely. One check to keep in mind is that the same table component being used in many different places. Please ensure that the functionality of all other tables is not broken, due to this change.

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by akshatvirmani** [comment]
Hi! I would like to work on this issue. Please assign this to me.

**Comment by Ankita28g** [comment]
HI @akshatvirmani assigned this to you! Happy hackfesting 😃

**Comment by Ankita28g** [comment]
sorry @akshatvirmani this issue is actually closed. can you pick another one?
