### ISSUE TITLE
⚡ Change filter for last seen in inventory page

### ISSUE THREAD

**Issue by notshivansh** [akto-api-security/akto#161]
💭 Introduction: The flter for 'last seen' in the API inventory shows the units in many different units and is not user friendly. 

🎯 Requirements:

✅ Task summary: 

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Implement a better filter which alleviates the user experience.
- [ ] Submit a pull request here.

💡 Hints:

- You can take inspiration from the filter implemented on sensitive data page for "discovered" field. <img width="378" alt="Screenshot 2023-03-21 at 1 08 21 PM" src="https://user-images.githubusercontent.com/112413532/226543251-95c510c7-d7ad-4dbb-8001-6b6eba103fdb.png"> 
- [server-table](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/shared/components/ServerTable.vue) is called from [SensitiveData.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/sensitive/SensitiveData.vue), where the headers along with "showFiiterMenu" parameter are passed. Try to implement a similar functionality on [API inventory page](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/inventory/components/APIEndpoints.vue) and [API changes Page](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/changes/Changes.vue) for ```last seen``` and ```discovered``` fields.

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by ankush-jain-akto** [comment]
This has been implemented by @Ark2307. Closing this issue
