### ISSUE TITLE
⚡ On settings page, support a query parameter for tab name

### ISSUE THREAD

**Issue by notshivansh** [akto-api-security/akto#164]
💭 Introduction: The settings page has a bunch of tabs. When the settings page is opened, the default tab is shown. 

🎯 Requirements:

- A basic understanding of vue.js

✅ Task summary: 

- [x] Ask to be assigned to the issue.
- [x] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Add a functionality to support tab name in the query parameter for the settings page. When this query parameter is passed in the url, with a tab name, that particular tab name should be opened instead of the default tab.
- [ ] Submit a pull request here.

💡 Hints and solving approach:

- The settings page (PageSettings.vue) has a "tab" prop being passed to it from router > index.js . This tab property is the query param from the settings page. This should be a number (i.e. the tab number to which you would like to be taken to). 
- All the tab names are sent to LayoutWithTabs.vue, which in turn shows the tab layout. The "tab" parameter mentioned above should be passed to LayoutWithTabs.vue, where the core logic should reside, as to which tab should be opened, based on the "tab" prop.

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by YashKumarVerma** [comment]
could this be assigned to me?

**Comment by notshivansh** [comment]
sure, If you need any help you can ping me on our discord server or comment on this issue itself.

**Comment by Ankita28g** [comment]
Thanks for your interest @YashKumarVerma. Happy hackfesting 🔥

**Comment by Ankita28g** [comment]
Hi @YashKumarVerma  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by ankush-jain-akto** [comment]
This has been implemented already. Closing the issue
