### ISSUE TITLE
⚡ Improve test run menu

### ISSUE THREAD

**Issue by notshivansh** [akto-api-security/akto#167]
💭 Introduction: Currently, when a user tries to run tests on an API collection, they are presented with a test menu with recommended tests selected. This is good for first time users but more advanced users want to run specific tests only on their api collections. 

🎯 Requirements:

-  A basic understanding of vue.js

✅ Task summary: 

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Show the test menu with no test selected by default instead of recommended selecting tests
- [ ] Add a "Select Recommended Tests" button in the test menu, which selects the the current recommended tests in the test menu
- [ ] Submit a pull request here

💡 Hints:

- The Tests are selected in the ```tests-selector``` (File: TestsSelector.vue) component and then sent to the ```schedule-box``` (File: ScheduleBox.vue) component, which sends an API request to run the selected tests.
- Try to add a ```select recommended tests``` checkbox in ```schedule-box``` component, which selects the recommended tests.
- By default these are selected in the mounted() for ```tests-selector``` using ```populateMapCategoryToSubcategory()``` function.
- Extract this out to be called only when the checkbox for ```select-recommended-tests``` is checked in the ```schedule-box``` component. 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by siddoinghisjob** [comment]
Hey can I get to work on this? I have worked in react and vue and would like to contribute if given chance.

**Comment by notshivansh** [comment]
Sure @siddoinghisjob. I'll assign this issue to you. 

Happy hacking.

**Comment by siddoinghisjob** [comment]
Please tell me where the file TestsSelector.vue and ScheduleBox.vue are located.

**Comment by notshivansh** [comment]
There you go, [TestSelector.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/inventory/components/TestsSelector.vue) and [ScheduleBox.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/shared/components/ScheduleBox.vue)

**Comment by Ankita28g** [comment]
Hi @siddoinghisjob do you need help here?

**Comment by siddoinghisjob** [comment]
Working on it.. sorry for the delay.. I am having my exams :(

**Comment by Ankita28g** [comment]
oh don't worry. all the best for exams!

**Comment by Ankita28g** [comment]
no worries @siddoinghisjob. let me know if you need help.

**Comment by ankush-jain-akto** [comment]
This has been solved already in the new UI
