### ISSUE TITLE
⛏️Write a test to execute bash commands via mass assignment

### ISSUE THREAD

**Issue by aktoboy** [akto-api-security/akto#172]
💭 Introduction:
We want to test whether we can execute bash commands via mass assignment [ref](https://github.com/OWASP/API-Security/blob/master/2019/en/src/0xa6-mass-assignment.md#scenario-2)

🎯 Requirements:
This test should only run for APIs which are taking bash commands as input.
The test should detect correctly whether we are able to successfully execute bash commands.

✅ Task summary:
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Fork the [tests-library](https://github.com/akto-api-security/tests-library) repository, create a new branch and commit the yaml file which will be called in your test.
- [ ] Fork the [akto](https://github.com/akto-api-security/akto) repo, create a new branch.
- [ ] Create a new Java class `ExecuteBashViaMassAssignment` which will contain the main logic related to the test in `akto>apps>testing>src>main>java>com>akto>rules` package. This class will extend `TestPlugin` class and you will need to override the `start` method. This method will contain the logic to filter the stored apis for which this test will be executed. Consider only those apis which have keys taking in bash command either in query params or request body and the stored responses should have a 2XX status code. Take a look at `PageSizeDosTest.java` for reference.
- [ ] Once we have apis which have cleared our filtering criteria, we should execute the yaml created previously by creating an object of FuzzingTest class and then calling `FuzzingTest`'s `runNucleiTest` method. 
- [ ] We will need to create a new subcategory for the newly added test in `GlobalEnums.java` file's `TestSubcategory` enum where we will describe the new test we are adding.
- [ ] Now we just need to call this test whenever user triggers testing. For this we need to create a object of the ExecuteBashViaMassAssignment class in `TestExecutor.java` file and then pass this object to the `runTest` method.
- [ ] Write unit tests to test your changes. 
- [ ] Submit both the PRs here.

✌🏻 Hints:
You can build the yaml template by referring this [PR](https://github.com/akto-api-security/tests-library/pull/7)
You can refer the PR here for changes to be done in akto repo: [link](https://github.com/akto-api-security/akto/pull/193)
Straight from OWASP [link](https://github.com/OWASP/API-Security/blob/master/2019/en/src/0xa6-mass-assignment.md#scenario-2)

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by 17Ankita2003jalli** [comment]
Hi, I have learnt java but haven't any idea about Testing . I am interested to work on this issue so can I get any help?

**Comment by oohsai** [comment]
I'd like to work on this Issue. Please Assign me this issue

**Comment by Cioraz** [comment]
Hey,
Can i be assigned to the issue?

**Comment by ankush-jain-akto** [comment]
Hi @Cioraz , @oohsai - this is an old issue and not relevant anymore. I will add more issues around Mass Assignment-related issues. 

I wanted to ask, would you be open to backend programming in Java? There are some beautiful pending items related to Mass Assignment vuln - but requires backend dev.
