### ISSUE TITLE
⚡️ Support postman collection upload 

### ISSUE THREAD

**Issue by ayushaga14** [akto-api-security/akto#177]
💭 Introduction:
Akto currently supports adding data to dashboard via postman. You can refer more in the documentation - https://docs.akto.io/add-api-data/integrations/postman. The task involves making postman data upload into a single step process. User should be able to export a collection in postman, and use that collection json file in Akto dashboard for uploading traffic data. 

🎯 Requirements:
Vue js
Java

✅ Task summary:

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Current login resides in PostmanAction.java, inside function importDataFromPostman, which is currently an api handler method. You would have to extract this out and make some part of this method generic so that current functionality and new functionality both work well.
- [ ] Write a new method in [PostmanAction.java](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/src/main/java/com/akto/action/PostmanAction.java). Observe the convertApiInAktoFormat method, which has the existing implementation.
- [ ] Add a new button inside Api Collection Page, clicking on which will trigger your new method. You can take some insight from the current har file upload button inside [ApiEndpoints.vue](https://github.com/akto-api-security/akto/blob/master/apps/dashboard/web/src/apps/dashboard/views/observe/inventory/components/APIEndpoints.vue) (tooltipText="Upload traffic (.har)"), and create a new button just next to it.
- [ ] Submit a pull request here.

✌🏻 Hints
Focus on convertApiInAktoFormat method inside PostmanAction.java. One way of solving this could be that the code after this method can be kept generic for both new and old implementations, and the code before this will be called only for current implementation. Happy Coding!

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by IamRaviTejaG** [comment]
Hi team! I would like to take a jab at this.

**Comment by piyushpandey2000** [comment]
can this still be picked?

**Comment by avneesh-akto** [comment]
Hello, @piyushpandey2000. I wanted to inform you that the issue has already been resolved.
