### ISSUE TITLE
⛏️ Write a test to do username enumeration attack

### ISSUE THREAD

**Issue by aktoboy** [akto-api-security/akto#178]
💭 Introduction:
We want to test whether an attacker can guess username via brute force attack.

🎯 Requirements:
1. Filters - This test should run on api which is used for login. API with `login` in the URL and `username` in one of query params or request body

2. Execute - It should replace the `username` with 1000 possible usernames. To understand how to use a wordlist in a YAML template, you can refer to [this example](https://github.com/akto-api-security/tests-library/blob/master/Security-Misconfiguration/DefaultLoginCredentials.yml#L29).
 
3. Validation - If the API response payload contains the word "limit", test passes. Otherwise, test fails. 

📚 Reading
You can find a detailed documentation of test editor rules [here](https://docs.akto.io/test-editor/test-yaml-syntax-detailed)
Find 100+ examples of YAML tests [here](https://github.com/akto-api-security/tests-library)

✅ Task summary:
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Signup for [Akto](https://app.akto.io/)
- [ ] Fork the [tests-library](https://github.com/akto-api-security/tests-library) repository, create a new branch and commit the yaml file which will be called in your test.
- [ ] Submit the PR here.

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by Dhruv9731** [comment]
@aktoboy I want to work on this issue. Please assign me.

**Comment by Ankita28g** [comment]
Thanks for your interest 🎉 @Dhruv9731 

Assigning to you! Happy hackfesting 🥳 @aktoboy will help you here.

**Comment by aktoboy** [comment]
Hey @Dhruv9731, let me know if you need some help with this issue.

**Comment by Ankita28g** [comment]
Hi @Dhruv9731 are you still working on this?

**Comment by Ankita28g** [comment]
Hi @Dhruv9731  thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

1. Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
2. Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by harshalkh** [comment]
@Ankita28g if it's still open I want to contribute on it.

**Comment by ankush-jain-akto** [comment]
Hi @harshalkh - Assigned this to you. However, the instructions are quite old here. Will be correcting them soon.

**Comment by harshalkh** [comment]
> Hi @harshalkh - Assigned this to you. However, the instructions are quite old here. Will be correcting them soon.

Let me know once you correct the instructions. So I can start..

**Comment by ankush-jain-akto** [comment]
Hi @harshalkh - updated the description of the task. Thanks for being patient.

**Comment by saatvikbhola** [comment]
hello, i'd like to work on it if its open

**Comment by harshalkh** [comment]
> Hi @harshalkh - updated the description of the task. Thanks for being patient.

@ankush-jain-akto will there be 2 PRs or only one to tests-library?

**Comment by harshalkh** [comment]
@ankush-jain-akto I have raised PR please review - https://github.com/akto-api-security/tests-library/pull/20

**Comment by avneesh-akto** [comment]
@harshalkh Test logic looks good. But there are some fields missing. Also don't limit to "username" enumerate on fields similar to username like email etc. Limit the wordlist size to maximum of 100 elements

**Comment by harshalkh** [comment]
> @harshalkh Test logic looks good. But there are some fields missing. Also don't limit to "username" enumerate on fields similar to username like email etc. Limit the wordlist size to maximum of 100 elements

@avneesh-akto Thanks for review. I have done changes as per suggestion. Please review and let me know.

**Comment by avneesh-akto** [comment]
Good work @harshalkh . Test template works as expected. Just change target branch to develop instead of master

**Comment by harshalkh** [comment]
> Good work @harshalkh . Test template works as expected. Just change target branch to develop instead of master

New PR raised, as changing Target was showing too many files.
Please review new PR-
https://github.com/akto-api-security/tests-library/pull/28

**Comment by avneesh-akto** [comment]
Thank you for submission @harshalkh  . Merged your PR. Happy hacking 🚀
