### ISSUE TITLE
⛏️ Write test for fetching metadata from a digital ocean instance

### ISSUE THREAD

**Issue by aktoboy** [akto-api-security/akto#228]
💭 Introduction:
We want to test whether API's which take in url as a param are vulnerable to fetch information related to compute engine using SSRF. You can refer [this](https://hackerone.com/reports/341876) blog for more details about the attack.

🎯 Requirements:
This test should only run for APIs which are taking url as a parameter in input.
The test should correctly detect whether some instance-related information can be fetched via an API specific to Digital Ocean cloud.
An example for AWS is implemented [here](https://github.com/akto-api-security/tests-library/blob/master/Server-Side-Request-Forgery/SSRFOnAwsMetaEndpoint.yaml) already.

📚 Reading

You can find a detailed documentation of test editor rules [here](https://docs.akto.io/test-editor/test-yaml-syntax-detailed)
Find 100+ examples of YAML tests [here](https://github.com/akto-api-security/tests-library)

✅ Task summary:
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Fork the [tests-library](https://github.com/akto-api-security/tests-library) repository, create a new branch and commit the yaml file which will be called in your test.
- [ ] Signup for [Akto](https://app.akto.io)
- [ ] Check in the `Attempt` tab, if the payload changes, then task is done.
- [ ] Submit the PR here.

✌🏻 Hints:
You can build the yaml template by referring this [link](https://github.com/bhavik-dand/tests-library/blob/temp/ssrf_aws_endpoint/SSRF/ssrf_aws_metadata_endpoint.yaml)

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by professorabhay** [comment]
Hai @aktoboy, I am just exploring issues and it seems interesting. Here its what I understand after walkthrough the bunch of files (mentioned above). It can be done by creating the `SSRFOnDigitalOceanMetadataEndpoint` class and call the method from `BaseSSRFTest.java`  as similar as `SSRFOnAwsMetadataEndpoint.java` and so on other steps.....

**Comment by mogulcoder26** [comment]
i want to solve this issue.

**Comment by Ankita28g** [comment]
Thanks for your interest @mogulcoder26. Assigning it to you

**Comment by rashmibharambe** [comment]
@Ankita28g @ankush-jain-akto @aktoboy - I have started looking at this issue, can you please assign this to me.

**Comment by rashmibharambe** [comment]
> @Ankita28g @ankush-jain-akto @aktoboy - I have started looking at this issue, can you please assign this to me.

@Ankita28g @ankush-jain-akto @avneesh-akto - I have raised PR - please check- https://github.com/akto-api-security/tests-library/pull/32

**Comment by avneesh-akto** [comment]
Good work @rashmibharambe. I have merged your PR. Feel free to work on other issues.

**Comment by avneesh-akto** [comment]
Good work @rashmibharambe. I have merged your PR. Feel free to work on other issues.
