### ISSUE TITLE
Add more case sensitive keys for page size DoS test

### ISSUE THREAD

**Issue by ankush-jain-akto** [akto-api-security/akto#229]
💭 Introduction:
The page size dos test looks for APIs with input keys like `pagesize` , `limit` etc. The test then modifies the value by 10X to check if the response has 10X more number of values. This kind of an attack can make the server unresponsive by asking for arbitrarily large number of objects. 

🎯 Requirements:

- Basic experience with **Java** 

✅ Task summary:

- [ ] Ask to be assigned to the issue. 
- [ ] Wait to be assigned. We will try to assign in less than 2 hours. 
- [ ] The keywords are in `PageSizeDosTest.java` and represented by variable [PAGINATED_KEYWORDS](https://github.com/akto-api-security/akto/blob/master/apps/testing/src/main/java/com/akto/rules/PageSizeDosTest.java#L32)
- [ ] Please add `perPage`, `pageSize` and `pageLimit` vars (case sensitive)
- [ ] _Optional_ : You can go an extra mile and make all comparisons case-insensitive. This is a bit more involved, but you can do it [here](https://github.com/akto-api-security/akto/blob/master/apps/testing/src/main/java/com/akto/rules/PageSizeDosTest.java#L63)
- [ ] Submit a pull request here
 

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by akshatvirmani** [comment]
Hi! In this issue do we just have to change "perpage" with "perPage" and make necessary changes regarding that?

**Comment by Ankita28g** [comment]
@LuD1161 Assigned to you!

**Comment by Ankita28g** [comment]
@akshatvirmani sorry this has been assigned already. can you pick something else?  😞

**Comment by LuD1161** [comment]
@Ankita28g I am up for it 🙌

**Comment by Ankita28g** [comment]
@LuD1161  Add details in this form for your [swags](https://forms.gle/Nam3PVREYoMuPTNH9)
