### ISSUE TITLE
📃 Write a blog post about testing for Mass Assignment using Akto

### ISSUE THREAD

**Issue by Ankita28g** [akto-api-security/akto#235]
# 💭 Introduction

Akto is an open source API security product. 

Your task is to write a blog post about testing for SSRF using Akto.

###  🎯 Requirements

- Your article has to be publicly available.
- Your article must tag Akto in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task summary:

-  Drop a comment on this issue indicating that you’re working on it.
-  Write a blog post with title  `How I tested for Mass Assignment using Akto?`
-  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
-  Submit a pull request here.
-  Share your work on social media and tag https://github.com/akto-api-security/akto (Reddit / HackerNews / Twitter / Facebook / Linkedin)

### 🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by bhavyastar** [comment]
Hey @Ankita28g, I am working on this issue. I will share the draft here and after that will publish my article.

**Comment by Ankita28g** [comment]
Awesome @bhavyastar! Assigned this to you. Happy hackfesting 🎉

**Comment by Ankita28g** [comment]
**FYI: Multiple people can be assigned to the issue**

**Comment by Ankita28g** [comment]
Hi @bhavyastar let us know if you need any help with this.

**Comment by Jittojoyes98** [comment]
Hii @bhavyastar , if you need help with the blog, iam ready to help.

**Comment by akashprajapatiroyal** [comment]
Hello, I am working on this.

**Comment by Ankita28g** [comment]
Yes! Assigned to you. Happy hackfesting 🎉

**Comment by akashprajapatiroyal** [comment]
Hello
@Ankita28g I have written blog. Here is the link to the blog :
https://akashprajapatiroyal.hashnode.dev/how-i-tested-for-mass-assignment-using-akto

**Comment by Ankita28g** [comment]
Hi @akashprajapatiroyal thank you so much! let me review it and get back

**Comment by akashprajapatiroyal** [comment]
Hello @Ankita28g will my contribution be considered?

**Comment by Ankita28g** [comment]
Hi @akashprajapatiroyal @bhavyastar thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

1. Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆 
2. Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!

**Comment by akashprajapatiroyal** [comment]
This Form is giving below response:

You need permission
This form can only be viewed by users in the owner's organization.

Try contacting the owner of the form if you think this is a mistake. [Learn More.]

**Comment by Ankita28g** [comment]
Check now ?

**Comment by akashprajapatiroyal** [comment]
Yes It's Working Now.
Thank You

**Comment by Ankita28g** [comment]
Github username

**Comment by akashprajapatiroyal** [comment]
Done👍

**Comment by Mannxxx** [comment]
Is this issue closed? If not, I would like to help.

**Comment by ankush-jain-akto** [comment]
Hi @Mannxxx - this is all false information. Please take it down. There is no such thing as `npm install -g akto`.

**Comment by Mannxxx** [comment]
@ankush-jain-akto, I'm truly disappointed by the misinformation that was shared, especially since it came from your own approved comment (For reference: https://github.com/akto-api-security/akto/issues/248).
Turns out there was no need for the negative comments on my blog post. I could have, on my own, taken it down once I became aware that this information was false.

Anyways, apologies for the misinformation.

**Comment by ankush-jain-akto** [comment]
Thanks @Mannxxx - FYI, we completed the task internally ourselves a few months ago. See the blog [here](https://www.akto.io/blog/how-to-test-mass-assignment-in-apis-using-akto)
