### ISSUE TITLE
gRPC with protobuf payloads is not supported

### ISSUE THREAD

**Issue by ogryb** [akto-api-security/akto#24]
gRPC is a popular approach to  building API's these days practiced by big tech and fintech companies, but it's not supported in the current Akto implementation.  To reproduce:

1. Install Akto plugin in BurpSuite with automatic export enabled
2. Install Akto Dashboard
3. Run a REST API with JSON payload in Burp's Repeater and observe that the export from Burp to Akto Dashboard works
4. Run an gRPC API with protobuf payload in Burp's repeater and observe that export to Dashboard doesn't work
5. Try exporting gRPC payload to HAR file in Burp's Akto Plugin and observe that 'entries' field is empty:

`{"log":{"version":"1.2","creator":{"name":"Akto","version":"3.19.2"},"pages":[],"entries":[]}}`

**Comment by Ankita28g** [comment]
Thanks @ogryb 

We have added this to the roadmap now for this quarter. https://github.com/orgs/akto-api-security/projects/8/views/1

**Comment by Ankita28g** [comment]
It's supported now in our latest release. Closing the issue
