### ISSUE TITLE
Few questions on API discovery

### ISSUE THREAD

**Issue by B1gM8c** [akto-api-security/akto#272]
Thank you for providing such powerful code. I still have a few questions and hope to get your reply. API endpoint discovery is usually a complex process. I saw that our project supports two ways of traffic mirroring or active discovery. My confusion here is whether our API discovery function will merge URLs like these:
```
www.example.com/api/v1/user/100
www.example.com/api/v1/user/200
www.example.com/api/v1/user/300
```
into an endpoint like this:
```
www.example.com/api/v1/user/{userid}
```
However, I have a doubt that when merging, it is also necessary to judge based on the relevant parameters in the request and response to improve the accuracy of merging.

In addition, there is another doubt that the API endpoint merger may not necessarily be at the end of the URL, but may also be the second to last or in other positions, such as:
```
www.example.com/api/v1/user/100/add
www.example.com/api/v1/user/200/add
www.example.com/api/v1/user/300/add
```
Are there any related code examples in the project for reference? Thank you very much for sharing generously.

**Comment by avneesh-akto** [comment]
Hi @B1gM8c . Thank you for checking out Akto. Yes we handle all such cases. Akto not only merges URLs based on integer parameters but it can also intelligently detect UUIDs and other form of unique resource IDs and merge them accordingly.

Cases handled by akto:

1. `api/user/1/name` && `api/user/2/name` ---> `api/user/{user_id}/name`
2. `api/org/09279d3ap8v/details`&& `api/org/0927aa8ce7cz/details` ---> `api/org/{org_id}/details`

We merge based on :
1. How similar URLs are
2. How similar their request response payloads are.

The code for mergin of URLs is in [APICatalogSync.java](https://github.com/akto-api-security/akto/blob/master/apps/api-runtime/src/main/java/com/akto/runtime/APICatalogSync.java). Specifically in the `mergeUrlsAndSave` method.

**Comment by B1gM8c** [comment]
I have a few more questions for you. Here, are API endpoints only selected based on 2XX response traffic, or will mirrored traffic with non-2XX responses also be recognized as API endpoints? Usually, attacks are non-2XX responses, so I'm not sure if our project can detect non-2XX API attacks.

**Comment by avneesh-akto** [comment]
We do get non-2xx traffic from mirroring and Burp. Akto ignores them to prevent inventory from getting polluted. 

Here is the [code snippet](https://github.com/akto-api-security/akto/blob/ba095944fb6c47fc564c2ed70cfd860b4111da93/apps/api-runtime/src/main/java/com/akto/parsers/HttpCallParser.java#L256) responsible for this. This code block specifically:

```
 boolean cond = HttpResponseParams.validHttpResponseCode(httpResponseParam.getStatusCode());
 if (!cond) continue;
```

So if you remove this code block you can still process non 2xx traffic. May I know why you are interested in non-2xx traffic to be shown in Akto dashboard.

**Comment by B1gM8c** [comment]
Thank you very much for your patient guidance. I'm actually more interested in API endpoint aggregation. I took a quick look at the code you provided and found that it seems to create templates based on the payload of the request and response. Can I assume that for each incoming request, a similar hash value, whether it's MD5 or SHA256, is generated? And when the results are merged, they are based on this hash value, which is used to combine the URLs. The advantage of this approach is that there is no need to enter a large number of URLs for comparison in advance, and real-time API endpoint aggregation can be achieved. Is this a correct understanding?

**Comment by avneesh-akto** [comment]
Nope.

We do not use the hash method you have mentioned because we are not looking for exact matching of request/response payloads. 

We perform a comparison between the request/response parameters of two APIs to identify similarities between them. When we detect a minimum of an 80% match between the parameters of the two APIs, we consider them as a pair and store them separately. We repeat this process until we have accumulated a collection of 10 unique pairs and then we merge them to form a single URL. The reason we wait for 10 unique pairs is to prevent over-merging.

I hope that my response has provided you with the information you were seeking. If you have any further questions or would like more detailed assistance, I invite you to join our [Discord](https://discord.com/invite/Wpc6xVME4s)

**Comment by B1gM8c** [comment]
Thank you very much for your selfless sharing. I have joined the Discord channel.

**Comment by avneesh-akto** [comment]
Awesome.


Closing this issue.
