### ISSUE TITLE
BurpSuite extension can not connect to akto

### ISSUE THREAD

**Issue by Fewword** [akto-api-security/akto#436]
I download Akto's Burp extension, then I add the downloaded jar file in extension tab, but i see 
`"Akto Burp plugin initialising..... 
imageURLMain: credentials.txt jar:file:/var/folders/5z/0jbkvh6s54nf_ppqv65cwm5w0000gn/T/burp10522404962378867565.tmp/6!/credentials.txt
REQUEST: {"version":"4"}"` in Output, and `"Error in sending health checkup: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $"` in Errors.

**Comment by avneesh-akto** [comment]
Hello @Fewword. Can you send me the jar file: avneesh@akto.io.

**Comment by Fewword** [comment]
Hello @avneesh-akto. I have sent the jar file.
