### ISSUE TITLE
Unexpected Application Error in Quick Start (new UI)

### ISSUE THREAD

**Issue by Chan9390** [akto-api-security/akto#586]
Steps to reproduce:
1. Switch to new UI
2. Click on "Quick Start", scroll to "Kubernetes Daemonset", click "Connect"
3. The application errors out

<img width="1429" alt="image" src="https://github.com/akto-api-security/akto/assets/12944530/421dd1bb-c43d-4135-be3b-fbb2ede9f9c1">

The same happens when trying to configure AWS Fargate, Nginx, EKS, Docker and TCP Agent. 

PS: I have configured AWS Mirroring and enabled for few LBs. Not sure if thats related to this bug.

**Comment by ankush-jain-akto** [comment]
Hi @Chan9390 - Thanks for reporting. @aktoboy (aka Bhavik) is working on this from our team. We will keep you updated about the fix. 

In the meantime, can you please try switching to the Legacy UI and try from there?

**Comment by ankush-jain-akto** [comment]
If you want to use `Kubernetes Daemonset` and you have already setup mirroring, you can directly proceed with applying `akto-daemonset-config.yml` in your application's Kubernetes cluster. https://docs.akto.io/traffic-connections/traffic-data-sources/kubernetes#setting-up-akto-daemonset-pod-on-your-k8s-cluster

**Comment by ankush-jain-akto** [comment]
Hi @Chan9390 - did this help? Please let us know.

**Comment by Ankita28g** [comment]
hi @Chan9390 this has been solved so we are marking this as closed.
