### ISSUE TITLE
[BUG] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [akto-api-security/akto#628]
**Screenshots ----------**

<img width="960" alt="Screenshot 2023-10-08 222842" src="https://github.com/akto-api-security/akto/assets/85905403/df46641c-e5fd-4c85-bb2e-478cdd239101">

<img width="960" alt="Screenshot 2023-10-08 223131" src="https://github.com/akto-api-security/akto/assets/85905403/ad33a227-53db-43df-880b-bbb5805a0603">

--------------------

@Ankita28g Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

**Comment by gauravsingh1281** [comment]
@Ankita28g Please assign this issue to me under hacktoberfest label.

**Comment by Ankita28g** [comment]
hi @gauravsingh1281 website is not under the scope. How about you find something with label `hacktoberfest`

also we use a no code tool to build the website.
