### ISSUE TITLE
One particular issue

### ISSUE THREAD

**Issue by Digita1ocean** [akto-api-security/akto#651]
I have been having issues with docker with akto,im unable to run localhost:9090.PLEASE IS THERE ANYWAY i CAN USE APACHE TO RUN THE localhost:9090 INSTEAD OF DOCKER.

**Comment by ankush-jain-akto** [comment]
Hi @Digita1ocean - you mean you don't want to run using Docker, but you want to compile locally and run it on 9090 port?

**Comment by Digita1ocean** [comment]
YES.IM SICK AND TIRED OF WHAT DOCKER IS DOING ON MY WINDOWS SYSTEM,SEVERAL ISSUES.PLEASE I NEED A WAY NOT TO USE DOCKER PLEASE.

**Comment by ankush-jain-akto** [comment]
Hi @Digita1ocean - Manual setup instructions are here - https://github.com/akto-api-security/akto#-manual-setup-instructions

Did you start with this? Where are you stuck exactly? I am happy to come on a quick call if that helps.
