### ISSUE TITLE
⛏️ Write a test to check whether we can create/update an object with Admin level Key-Value Pairs

### ISSUE THREAD

**Issue by arjun-akto** [akto-api-security/akto#656]
💭 Introduction:

We want a test to check whether an attacker can create/update entity with Admin level Key-Value Pairs.

🎯 Requirements:

1. Filters - API with atleast one parameter with value as an input in GET query parameter or JSON body parameter

2. Execute - It should add a value with
- `is_admin` = True
- `is_administrator` = True
- `isAdmin` = True
- `approved` = True

You can refer to more parameters via [[Link](https://github.com/s0md3v/Arjun)] or [[Link](https://owasp.boireau.io/4-web_application_security_testing/07-input_validation_testing/20-testing_for_mass_assignment)]
    
3. Validation - If the application responds with a exception trace or error response strings, it is a vulnerability. 

✅ Task summary:

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned. We will try to assign in less than 2 hours.
- [ ]  Signup for [[Akto](https://app.akto.io/)]
- [ ]  Fork the [[tests-library](https://github.com/akto-api-security/tests-library)] repository, create a new branch and commit the yaml file which will be called in your test.
- [ ]  Submit both the PR here.

📚 Reading

You can find a detailed documentation of test editor rules [[here](https://docs.akto.io/test-editor/test-yaml-syntax-detailed)]

Find 100+ examples of YAML tests [[here](https://github.com/akto-api-security/tests-library)]

🙋🏼‍♂️ Questions:

If you have questions, need any help, or just want to hang out, make sure to join us on our [[Discord server](https://discord.com/invite/Wpc6xVME4s)].

**Comment by coder-oj** [comment]
hi @arjun-akto , I would like to try this out

**Comment by arjun-akto** [comment]
Hi @coder-oj . I have assigned the issue to you. Please feel free to connect us on our [Discord server](https://discord.com/invite/Wpc6xVME4s) for any doubts.

**Comment by rashmibharambe** [comment]
> hi @arjun-akto , I would like to try this out

@coder-oj - are you still looking to contribute for this issue? Or can I pick this up? @arjun-akto

**Comment by avneesh-akto** [comment]
I've assigned it to you, @rashmibharambe  . Happy hacking! Feel free to join our [Discord](https://discord.com/channels/1070706429402562733/1095281477748543618) if you need assistance.

**Comment by rashmibharambe** [comment]
@avneesh-akto can you please check this PR.

**Comment by avneesh-akto** [comment]
Invalid template dude. You need to add some kind of regex matching. Check out SSTIInTwig test

**Comment by rashmibharambe** [comment]
> Invalid template dude. You need to add some kind of regex matching. Check out SSTIInTwig test

Regex added...

**Comment by avneesh-akto** [comment]
Thank you for submission @rashmibharambe . Merged your PR. Happy hacking 🚀

**Comment by RaagaAkto** [comment]
Hi @rashmibharambe, please fill out[ this form here ](https://forms.gle/8d7B42XEJKePDwnn7)so we can send you Akto swags. Will let you know ETA of swags soon, thanks for your contribution! 🚀

**Comment by RaagaAkto** [comment]
Hi @rashmibharambe, we've received your details, swags should reach you in a month!
