### ISSUE TITLE
Delete/Edit API Testing

### ISSUE THREAD

**Issue by baicaiyihao** [akto-api-security/akto#675]
I want to delete the test results that I don't think are necessary, but the page doesn't seem to have this feature.
![图片](https://github.com/akto-api-security/akto/assets/31963442/889ff3e6-258a-464a-89d4-bd3da9a24cbc)

**Comment by avneesh-akto** [comment]
Hi @baicaiyihao thank you for trying out Akto. Currently Akto doesn't support deletion of test results.

**Comment by baicaiyihao** [comment]
Hi @avneesh-akto , will you consider adding this feature in future versions?

**Comment by avneesh-akto** [comment]
It's in our pipeline we will surely prioritise.
