### ISSUE TITLE
uploadHar Error

### ISSUE THREAD

**Issue by kraken01100** [akto-api-security/akto#676]
Hello, I installed Akto in Docker, but when I want to collect data, it gives the error in the picture. What is the reason for this? Thanks.

[https://imgur.com/a/0bQhLZC](url)

**Comment by avneesh-akto** [comment]
Can u share the screenshot of the "options" tab in Burp?

**Comment by kraken01100** [comment]
Of course https://imgur.com/lineVlV

**Comment by kraken01100** [comment]
and burp https://imgur.com/LmZB8kY

**Comment by kraken01100** [comment]
its work. Thanks a lot!

**Comment by avneesh-akto** [comment]
Awesome!! Closing the issue

cc: @ankush-jain-akto
