### ISSUE TITLE
Inadequate Spacing Between Vulnerabilities and Use Cases in Website Footer

### ISSUE THREAD

**Issue by moheyt** [akto-api-security/akto#686]
Issue Description:

The website's footer section currently exhibits a user interface and user experience issue related to improper spacing between the "Vulnerabilities" and "Use Cases" links. This lack of adequate spacing impacts the overall visual appeal and readability of the footer area, potentially confusing and inconveniencing users.

Steps to Reproduce:

1. Visit the website's homepage.
2. Scroll down to the footer section.
3. 
Current Behavior:

In the footer section of the website, the "Vulnerabilities" and "Use Cases" links are placed closely together, with minimal spacing in between. This leads to a cramped and cluttered appearance that may make it difficult for users to distinguish between the two links at first glance.

Expected Behavior:

The "Vulnerabilities" and "Use Cases" links in the website's footer should have adequate spacing between them. This spacing would improve the overall user experience, making it easier for visitors to identify and click on the links they are interested in.

Screenshots/Attachments:

![Screenshot 2023-10-24 203449](https://github.com/akto-api-security/akto/assets/85775976/a957c7fd-9b09-4361-9895-3ed6170b2472)

Additional Information:

This spacing issue affects the aesthetics and usability of the website. It is recommended to enhance the spacing between "Vulnerabilities" and "Use Cases" links in the footer section to ensure a more visually appealing and user-friendly experience.

Impact:

Decreased user experience: Users may find it difficult to navigate the website's footer, potentially leading to frustration and reduced engagement.
Aesthetic concerns: The cramped appearance can impact the website's overall visual appeal and professionalism.
Suggested Resolution:

The suggested resolution is to review and update the website's CSS or layout to provide proper spacing between the "Vulnerabilities" and "Use Cases" links in the footer section. The goal is to achieve a cleaner and more user-friendly design that enhances the user experience.

Additional Comments:

It is important to prioritize and address this spacing issue to ensure that the website provides a seamless and visually appealing experience to its visitors. Proper spacing is a fundamental aspect of good UI and UX design.

**Comment by moheyt** [comment]
I would like to take this issue. #hactoberfest

**Comment by adarsh-jha-dev** [comment]
Hey @moheyt , could you please assign me this issue?

**Comment by avneesh-akto** [comment]
The code for akto.io website isn't open sourced. Closing this issue
