### ISSUE TITLE
Request to Update Twitter Logo in Footer Section

### ISSUE THREAD

**Issue by moheyt** [akto-api-security/akto#687]
I have identified that the Twitter logo displayed in the footer section of website is outdated, and it is crucial to keep branding up to date with the latest elements provided by Twitter.

![Screenshot 2023-10-24 204651](https://github.com/akto-api-security/akto/assets/85775976/9a044cc8-8406-44b6-91e6-422fbc6c2025)

**Comment by moheyt** [comment]
I would like to take this issue. #hactoberfest

**Comment by Ganeshkharde1** [comment]
I can solve this issue

**Comment by avneesh-akto** [comment]
Not required.
