### ISSUE TITLE
In README.md instead of hackfest issue we should add hacktoberfest issue badge

### ISSUE THREAD

**Issue by BandhiyaHardik** [akto-api-security/akto#698]
Hackfest ended on 3rdApril 
![image](https://github.com/akto-api-security/akto/assets/110784317/9d4d71a7-54d1-412f-89ae-35b8dc85e5e4)

Current Badge:
![image](https://github.com/akto-api-security/akto/assets/110784317/b6a66aa4-f1b6-49b4-95f8-f58af9d6202d)

Hacktoberfest is going on so we should change it to hacktoberfest issues:
![image](https://github.com/akto-api-security/akto/assets/110784317/69ae8b0c-78b6-4661-83e1-88e93226700f)

**Comment by BandhiyaHardik** [comment]
can i work on this issue ?

**Comment by avneesh-akto** [comment]
Hey we will do this internally. Thank you for pointing it out. You can work on it in the meantime
