### ISSUE TITLE
Add Docker compose file and the env to the repo

### ISSUE THREAD

**Issue by SandeepSrinivasan** [akto-api-security/akto#75]
Please add the Compose and env files of the docker to the repo, so that it will be easy to clone the entire project and run the docker compose-up command to run the application.

``I'm raising a PR for the same. ``

Is there any particular reason why your team didn't add compose and env files along with the repo?

**Comment by SandeepSrinivasan** [comment]
[https://github.com/akto-api-security/akto/pull/76](url)

**Comment by Ankita28g** [comment]
Thank you so much for the contribution! The changes have been merged 👍

**Comment by SandeepSrinivasan** [comment]
Please assign this to me, So that it will be easy for to track later @Ankita28g

**Comment by Ankita28g** [comment]
Done. Happy hackfesting 🎉

**Comment by Ankita28g** [comment]
Thank you so much for the contribution! The changes have been merged. ❤️
