### ISSUE TITLE
Fail to Sign Up

### ISSUE THREAD

**Issue by resource-not-found-blank** [akto-api-security/akto#877]
Hello!
I tried following the instructions provided at https://docs.akto.io/getting-started/local-deploy
Afterward, I went to this page: http://localhost:9090/signup
I entered email and password -> Error: "Please ask the admin to invite you."

**Comment by avneesh-akto** [comment]
Hi @resource-not-found-blank 

Akto allows only 1 user to signup and others have to be invited. So I think you must have signed up earlier, use those credentials to sign in back again.

**Comment by mithu36** [comment]
@avneesh-akto 

same issue for me also. i forgot the password. so i tried to  signup with new mail id. and it shows "Please ask the admin to invite you."
how can i reset the password or solve this issue??
