### ISSUE TITLE
⛏️ Write a test to fetch schema of a GraphQL API

### ISSUE THREAD

**Issue by ankush-jain-akto** [akto-api-security/akto#91]
💭 Introduction:

🎯 Requirements:

✅ Task summary:
Write an API test to check if GraphQL introspection query is enabled. Please provide the following - 

1. Reference URL - where you took the inspiration
2. A Nuclei template similar to [this](https://github.com/akto-api-security/tests-library/blob/master/Misconfiguration/configs/prometheus-metrics.yaml) or a Java template similar to [this](https://github.com/akto-api-security/tests-library/blob/master/BOLA/business-logic/AddUserIdTest.java)

✌🏻 Hints:

1. Write a level-1 test to just fetch query names using query `{__schema{queryType{fields{name}}}}`
2. Write a ninja-query to fetch everything 

> `"fragment FullType on __Type {\n  kind\n  name\n  fields(includeDeprecated: true) {\n    name\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\nfragment InputValue on __InputValue {\n  name\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\nquery IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n"`

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

**Comment by marksowell** [comment]
1. Reference URL - https://infosecwriteups.com/hacking-graphql-part-1-61d7a31b30c3
2. Test #akto-api-security/tests-library#9

**Comment by Ankita28g** [comment]
Hi @marksowell thanks for your submission in Hackfest. 🔥 We are reviewing your work. Do these two below:

Join this group on [discord](https://discord.com/channels/1070706429402562733/1095281477748543618) for discussions around prizes? 🚀 🏆
Please fill this [form](https://forms.gle/fLXPKAJ8xcK9FhVP7) your PR to be considered for prizes!
