### ISSUE TITLE
Error generating the Vulnerability Report post the test

### ISSUE THREAD

**Issue by extensure123** [akto-api-security/akto#922]
I've started exploring this wonderful opensource project. I have setup the latest version of Akto locally using docker-compose and able to access the dashboard. at http://<my_ip>:9090

Steps
1) As part of the quick start instructions, I've selected "Postman" as the data source and successfully imported postman collection file (with "Allow Akto to replay API requests if responses are not found" enabled) 
2) Go to API Inventory -> API Collection and click on "Run Test"
3) Go to Testing-> Results and click on the test run name. I see that it ran 208 tests and found 4 vulnerabilities (screenshot attached)
4) When I click on "Export Vulnerability Report" it does not reflect the summary and vulnerability details. Instead an error message pops up "invalid test summary id" - screenshot attached. 

Appreciate inputs.
![Test_Results](https://github.com/akto-api-security/akto/assets/94514187/c3c10689-53ef-4a19-bdc3-671d19bd8b1a)
![vulnerability report error](https://github.com/akto-api-security/akto/assets/94514187/966f587e-7d78-412d-9efd-f3a095605bf5)

**Comment by ankush-jain-akto** [comment]
Hi @extensure123 - update on this issue - we have identified the root cause. Will release a fix today.

**Comment by extensure123** [comment]
@ankush-jain-akto - Thanks for the RCA to address this - look forward to the fix that I can validate and confirm once released.

**Comment by extensure123** [comment]
@ankush-jain-akto - Have we identified the root cause? Is the fix pending? I'm assuming it's related to the TO DO below in StartTestAction.java that may be throwing the above error
```
    public String fetchVulnerableTestRunResults() {
        ObjectId testingRunResultSummaryId;
        try {
            testingRunResultSummaryId = new ObjectId(testingRunResultSummaryHexId);
            Bson filters = Filters.and(
                    Filters.eq(TestingRunResult.TEST_RUN_RESULT_SUMMARY_ID, testingRunResultSummaryId),
                    Filters.eq(TestingRunResult.VULNERABLE, true));
            List<TestingRunResult> testingRunResultList = TestingRunResultDao.instance.findAll(filters, skip, 50, null);
            Map<String, String> sampleDataVsCurlMap = new HashMap<>();
            for (TestingRunResult runResult: testingRunResultList) {
                List<GenericTestResult> testResults = new ArrayList<>();
                // todo: fix
```

**Comment by ankush-jain-akto** [comment]
Hi @extensure123 . 

We have identified the root cause. There are some tests that require multiple API calls to be fired. If your test suite contains any of those tests, the "export report" will fail.

We have a fix ready here - https://github.com/akto-api-security/akto/pull/930. Will merge and deploy today.

**Comment by ankush-jain-akto** [comment]
This is deployed @extensure123 . Can you please check now? You might have to take the latest pull

**Comment by extensure123** [comment]
Thanks @ankush-jain-akto
I've pulled the latest versions today and re-ran the docker-compose from scratch.  I'm using the below tags for my local setup and all the containers are up and running but unfortunately I'm unable to check it as the dashboard at http://<my_ip>:9090 is now not accessible.

**Seems there's a new issue with the dashboard based on the latest version.  Is it?**

```
# docker images
REPOSITORY                                 TAG           IMAGE ID       CREATED         SIZE
aktosecurity/akto-api-testing              local         77cdcb4871e6   5 days ago      473MB
aktosecurity/akto-api-security-dashboard   local         33b32c81a51f   5 days ago      689MB
aktosecurity/akto-puppeteer-replay         latest        5cacbc66a78f   11 months ago   647MB
mongo                                      6.0.1         d34d21a9eb5b   18 months ago   693MB

```
```
# docker-compose ps
NAME                                 COMMAND                    SERVICE                       STATUS              PORTS
akto-akto-api-security-dashboard-1   "/docker-entrypoint.…"     akto-api-security-dashboard   running             0.0.0.0:9090->8080/tcp, :::9090->8080/tcp
akto-akto-api-security-testing-1     "/bin/sh -c '\"java\" …"   akto-api-security-testing     running
akto-akto-puppeteer-replay-1         "node test.mjs"            akto-puppeteer-replay         running             0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
mongo                                "docker-entrypoint.s…"     mongo                         running             0.0.0.0:27017->27017/tcp, :::27017->27017/tcp
```

**Comment by ankush-jain-akto** [comment]
Hi @extensure123 . 

Can you please send a screenshot of the error ? 
Also, it will be of great help if you can send me your dashboard's docker logs as well. 

You can share them at support@akto.io

**Comment by extensure123** [comment]
These are the docker logs for dashboard. The login page does not let move past after I enter the earlier working account details (email and password) and click on sign-in.
**Note**: I'm using the **local tag for the akto images** based on the default docker-compose.yml. I also see a recent commit made in `apps/dashboard/web/polaris_web/web/src/apps/main/App.js` to import TokenValidator - not sure if it has anything to do with this login issue based on latest release.

```
[pool-3-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:6}] to mongo:27017
[pool-2-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:7}] to mongo:27017
[pool-2-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:8}] to mongo:27017
[pool-5-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:6, serverValue:9}] to mongo:27017
2024-03-21 04:39:10.169:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@6536e911{dashboard,/,file:///tmp/jetty-0_0_0_0-8080-root_war-_-any-2082744647134509655/webapp/,AVAILABLE}{dashboard.war}
2024-03-21 04:39:10.196:INFO:oejs.AbstractConnector:main: Started ServerConnector@24a1c17f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-03-21 04:39:10.196:INFO:oejs.Server:main: Started @35877ms
[pool-2-thread-1] ERROR com.akto.utils.GithubSync - Err msg: Failed to download the zip archive from url https://github.com/akto-api-security/tests-library/archive/refs/heads/master.zip. Error PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Class: sun.security.ssl.Alert
File: Alert.java
Line: 131
[pool-2-thread-1] INFO com.akto.utils.TestTemplateUtils - Failed to load test templates from github, trying to load from local directory
[pool-2-thread-1] INFO com.akto.listener.InitializerListener - Loading template files from directory
[pool-2-thread-1] INFO com.akto.utils.TestTemplateUtils - Loaded test templates from local directory
in Home::execute: settings IS_SAAS to false
[qtp1579572132-12] INFO com.akto.filter.LoggingFilter - url=/;method=GET;statusCode=200;username=null;ip=10.77.226.79
[qtp1579572132-14] INFO com.akto.filter.LoggingFilter - url=/public/akto_name_with_logo.svg;method=GET;statusCode=200;username=null;ip=10.77.226.79
[qtp1579572132-10] INFO com.akto.filter.LoggingFilter - url=/public/productss.png;method=GET;statusCode=200;username=null;ip=10.77.226.79
[qtp1579572132-15] INFO com.akto.filter.LoggingFilter - url=/public/favicon.svg;method=GET;statusCode=200;username=null;ip=10.77.226.79
[qtp1579572132-16] INFO com.akto.action.LoginAction - LoginAction Hit
[qtp1579572132-16] INFO com.akto.action.LoginAction - Auth Failed
[qtp1579572132-16] INFO com.akto.filter.LoggingFilter - url=/auth/login;method=POST;statusCode=401;username=null;ip=10.77.226.79
```

**Comment by ankush-jain-akto** [comment]
Checking @extensure123

**Comment by extensure123** [comment]
@ankush-jain-akto - The fix works now. I was able to validate the fix successfully.
The only thing I observed in the docker logs for the dashboard was the below .... assume it can be ignored

```
[pool-2-thread-1] ERROR com.akto.utils.GithubSync - Err msg: Failed to download the zip archive from url https://github.com/akto-api-security/tests-library/archive/refs/heads/master.zip. Error PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Class: sun.security.ssl.Alert
File: Alert.java
Line: 131
[pool-2-thread-1] INFO com.akto.utils.TestTemplateUtils - Failed to load test templates from github, trying to load from local directory
[pool-2-thread-1] INFO com.akto.listener.InitializerListener - Loading template files from directory
[pool-2-thread-1] INFO com.akto.utils.TestTemplateUtils - Loaded test templates from local directory
in Home::execute: settings IS_SAAS to false
```

Screenshot below of the working fix.
**Let me know if you need anything else to check from my end before I close this issue.** 
Thanks for your support.

<img width="769" alt="image" src="https://github.com/akto-api-security/akto/assets/94514187/55d982f0-d8a9-436e-8fe2-92a0771f7def">

**Comment by ankush-jain-akto** [comment]
Thanks @extensure123 😄  Good luck 👍 
I am closing the issue now
